/* 
 * Qlik NPrinting API
 *
 * You can extend your reporting system by using the Qlik NPrinting API. This API provides endpoints to perform operations on apps, On-Demand requests and results, reports, filters, and so on.  For all requests, the data returned is filtered based on user permissions. That is, if a user is not authorized to access a certain object, that object is not returned in the reponse.  API Stability: Experimental.  Deprecation period: None. Can change at any point and should be used only to evaluate upcoming functionality.     
 *
 * OpenAPI spec version: 0.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using Qlik.NPrinting.Rest.Client.Client;
using Qlik.NPrinting.Rest.Client.Model;
using RestSharp;

namespace Qlik.NPrinting.Rest.Client.Api
{
    
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRolesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get the roles.
        /// </summary>
        /// <remarks>
        /// Returns the list of all roles. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolename">The role name to use as a filter. (optional)</param>
        /// <param name="enabled">Indicates whether to retrieve the active roles (true) or inactive roles (false). (optional)</param>
        /// <param name="sort">A comma separated list of fields to use for sorting the entries. Allowed field values are \&quot;name\&quot; and \&quot;description\&quot;. Fields can be prefixed by \&quot;+\&quot; and \&quot;-\&quot; to indicate, respectively, ascending and descending order.  Usage example: /roles?sort&#x3D;+name,-description  (optional)</param>
        /// <param name="offset">The number of entries to skip. Default is 0. (optional, default to 0)</param>
        /// <param name="limit">The maximum number of entries to return. Default is 50. (optional, default to 50)</param>
        /// <returns>RoleListResponse</returns>
        RoleListResponse RolesGet (string rolename = null, bool? enabled = null, string sort = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Get the roles.
        /// </summary>
        /// <remarks>
        /// Returns the list of all roles. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolename">The role name to use as a filter. (optional)</param>
        /// <param name="enabled">Indicates whether to retrieve the active roles (true) or inactive roles (false). (optional)</param>
        /// <param name="sort">A comma separated list of fields to use for sorting the entries. Allowed field values are \&quot;name\&quot; and \&quot;description\&quot;. Fields can be prefixed by \&quot;+\&quot; and \&quot;-\&quot; to indicate, respectively, ascending and descending order.  Usage example: /roles?sort&#x3D;+name,-description  (optional)</param>
        /// <param name="offset">The number of entries to skip. Default is 0. (optional, default to 0)</param>
        /// <param name="limit">The maximum number of entries to return. Default is 50. (optional, default to 50)</param>
        /// <returns>ApiResponse of RoleListResponse</returns>
        ApiResponse<RoleListResponse> RolesGetWithHttpInfo (string rolename = null, bool? enabled = null, string sort = null, int? offset = null, int? limit = null);
        /// <summary>
        /// Get a specific role.
        /// </summary>
        /// <remarks>
        /// Returns the role specified by the &#x60;id&#x60; parameter. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the role.</param>
        /// <returns>RoleResponseData</returns>
        RoleResponseData RolesIdGet (string id);

        /// <summary>
        /// Get a specific role.
        /// </summary>
        /// <remarks>
        /// Returns the role specified by the &#x60;id&#x60; parameter. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the role.</param>
        /// <returns>ApiResponse of RoleResponseData</returns>
        ApiResponse<RoleResponseData> RolesIdGetWithHttpInfo (string id);
        /// <summary>
        /// Gets the roles for a user.
        /// </summary>
        /// <remarks>
        /// Returns the ordered list of role IDs for the specified user. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <returns>List&lt;Guid&gt;</returns>
        GenericIdListDataResponse UsersIdRolesGet (string id);

        /// <summary>
        /// Gets the roles for a user.
        /// </summary>
        /// <remarks>
        /// Returns the ordered list of role IDs for the specified user. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <returns>ApiResponse of List&lt;Guid&gt;</returns>
        ApiResponse<GenericIdListDataResponse> UsersIdRolesGetWithHttpInfo (string id);
        /// <summary>
        /// Updates the roles for a user.
        /// </summary>
        /// <remarks>
        /// Updates the list of role IDs for the specified user. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <param name="body">The unordered list of roles for the specified user.</param>
        /// <returns></returns>
        void UsersIdRolesPut (string id, List<Guid> body);

        /// <summary>
        /// Updates the roles for a user.
        /// </summary>
        /// <remarks>
        /// Updates the list of role IDs for the specified user. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <param name="body">The unordered list of roles for the specified user.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> UsersIdRolesPutWithHttpInfo (string id, List<Guid> body);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get the roles.
        /// </summary>
        /// <remarks>
        /// Returns the list of all roles. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolename">The role name to use as a filter. (optional)</param>
        /// <param name="enabled">Indicates whether to retrieve the active roles (true) or inactive roles (false). (optional)</param>
        /// <param name="sort">A comma separated list of fields to use for sorting the entries. Allowed field values are \&quot;name\&quot; and \&quot;description\&quot;. Fields can be prefixed by \&quot;+\&quot; and \&quot;-\&quot; to indicate, respectively, ascending and descending order.  Usage example: /roles?sort&#x3D;+name,-description  (optional)</param>
        /// <param name="offset">The number of entries to skip. Default is 0. (optional, default to 0)</param>
        /// <param name="limit">The maximum number of entries to return. Default is 50. (optional, default to 50)</param>
        /// <returns>Task of RoleListResponse</returns>
        System.Threading.Tasks.Task<RoleListResponse> RolesGetAsync (string rolename = null, bool? enabled = null, string sort = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Get the roles.
        /// </summary>
        /// <remarks>
        /// Returns the list of all roles. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolename">The role name to use as a filter. (optional)</param>
        /// <param name="enabled">Indicates whether to retrieve the active roles (true) or inactive roles (false). (optional)</param>
        /// <param name="sort">A comma separated list of fields to use for sorting the entries. Allowed field values are \&quot;name\&quot; and \&quot;description\&quot;. Fields can be prefixed by \&quot;+\&quot; and \&quot;-\&quot; to indicate, respectively, ascending and descending order.  Usage example: /roles?sort&#x3D;+name,-description  (optional)</param>
        /// <param name="offset">The number of entries to skip. Default is 0. (optional, default to 0)</param>
        /// <param name="limit">The maximum number of entries to return. Default is 50. (optional, default to 50)</param>
        /// <returns>Task of ApiResponse (RoleListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RoleListResponse>> RolesGetAsyncWithHttpInfo (string rolename = null, bool? enabled = null, string sort = null, int? offset = null, int? limit = null);
        /// <summary>
        /// Get a specific role.
        /// </summary>
        /// <remarks>
        /// Returns the role specified by the &#x60;id&#x60; parameter. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the role.</param>
        /// <returns>Task of RoleResponseData</returns>
        System.Threading.Tasks.Task<RoleResponseData> RolesIdGetAsync (string id);

        /// <summary>
        /// Get a specific role.
        /// </summary>
        /// <remarks>
        /// Returns the role specified by the &#x60;id&#x60; parameter. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the role.</param>
        /// <returns>Task of ApiResponse (RoleResponseData)</returns>
        System.Threading.Tasks.Task<ApiResponse<RoleResponseData>> RolesIdGetAsyncWithHttpInfo (string id);
        /// <summary>
        /// Gets the roles for a user.
        /// </summary>
        /// <remarks>
        /// Returns the ordered list of role IDs for the specified user. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <returns>Task of List&lt;Guid&gt;</returns>
        System.Threading.Tasks.Task<GenericIdListDataResponse> UsersIdRolesGetAsync (string id);

        /// <summary>
        /// Gets the roles for a user.
        /// </summary>
        /// <remarks>
        /// Returns the ordered list of role IDs for the specified user. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <returns>Task of ApiResponse (List&lt;Guid&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<GenericIdListDataResponse>> UsersIdRolesGetAsyncWithHttpInfo (string id);
        /// <summary>
        /// Updates the roles for a user.
        /// </summary>
        /// <remarks>
        /// Updates the list of role IDs for the specified user. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <param name="body">The unordered list of roles for the specified user.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task UsersIdRolesPutAsync (string id, List<Guid> body);

        /// <summary>
        /// Updates the roles for a user.
        /// </summary>
        /// <remarks>
        /// Updates the list of role IDs for the specified user. 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <param name="body">The unordered list of roles for the specified user.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UsersIdRolesPutAsyncWithHttpInfo (string id, List<Guid> body);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RolesApi : IRolesApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        public RolesApi(ApiClient apiClient)
        {
            ApiClient = apiClient;

            ExceptionFactory = ApiClient.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.ApiClient.RestClient.BaseUrl.ToString();
        }



        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ApiClient ApiClient { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get the roles. Returns the list of all roles. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolename">The role name to use as a filter. (optional)</param>
        /// <param name="enabled">Indicates whether to retrieve the active roles (true) or inactive roles (false). (optional)</param>
        /// <param name="sort">A comma separated list of fields to use for sorting the entries. Allowed field values are \&quot;name\&quot; and \&quot;description\&quot;. Fields can be prefixed by \&quot;+\&quot; and \&quot;-\&quot; to indicate, respectively, ascending and descending order.  Usage example: /roles?sort&#x3D;+name,-description  (optional)</param>
        /// <param name="offset">The number of entries to skip. Default is 0. (optional, default to 0)</param>
        /// <param name="limit">The maximum number of entries to return. Default is 50. (optional, default to 50)</param>
        /// <returns>RoleListResponse</returns>
        public RoleListResponse RolesGet (string rolename = null, bool? enabled = null, string sort = null, int? offset = null, int? limit = null)
        {
             ApiResponse<RoleListResponse> localVarResponse = RolesGetWithHttpInfo(rolename, enabled, sort, offset, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the roles. Returns the list of all roles. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolename">The role name to use as a filter. (optional)</param>
        /// <param name="enabled">Indicates whether to retrieve the active roles (true) or inactive roles (false). (optional)</param>
        /// <param name="sort">A comma separated list of fields to use for sorting the entries. Allowed field values are \&quot;name\&quot; and \&quot;description\&quot;. Fields can be prefixed by \&quot;+\&quot; and \&quot;-\&quot; to indicate, respectively, ascending and descending order.  Usage example: /roles?sort&#x3D;+name,-description  (optional)</param>
        /// <param name="offset">The number of entries to skip. Default is 0. (optional, default to 0)</param>
        /// <param name="limit">The maximum number of entries to return. Default is 50. (optional, default to 50)</param>
        /// <returns>ApiResponse of RoleListResponse</returns>
        public ApiResponse< RoleListResponse > RolesGetWithHttpInfo (string rolename = null, bool? enabled = null, string sort = null, int? offset = null, int? limit = null)
        {

            var localVarPath = ApiClient.ApiPathPrefix + "/roles";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new Dictionary<string, string>();
            var localVarHeaderParams = new Dictionary<string, string>(this.ApiClient.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType =this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept =this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (rolename != null) localVarQueryParams.Add("rolename", this.ApiClient.ParameterToString(rolename)); // query parameter
            if (enabled != null) localVarQueryParams.Add("enabled", this.ApiClient.ParameterToString(enabled)); // query parameter
            if (sort != null) localVarQueryParams.Add("sort", this.ApiClient.ParameterToString(sort)); // query parameter
            if (offset != null) localVarQueryParams.Add("offset", this.ApiClient.ParameterToString(offset)); // query parameter
            if (limit != null) localVarQueryParams.Add("limit", this.ApiClient.ParameterToString(limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RolesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RoleListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RoleListResponse) this.ApiClient.Deserialize(localVarResponse, typeof(RoleListResponse)));
            
        }

        /// <summary>
        /// Get the roles. Returns the list of all roles. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolename">The role name to use as a filter. (optional)</param>
        /// <param name="enabled">Indicates whether to retrieve the active roles (true) or inactive roles (false). (optional)</param>
        /// <param name="sort">A comma separated list of fields to use for sorting the entries. Allowed field values are \&quot;name\&quot; and \&quot;description\&quot;. Fields can be prefixed by \&quot;+\&quot; and \&quot;-\&quot; to indicate, respectively, ascending and descending order.  Usage example: /roles?sort&#x3D;+name,-description  (optional)</param>
        /// <param name="offset">The number of entries to skip. Default is 0. (optional, default to 0)</param>
        /// <param name="limit">The maximum number of entries to return. Default is 50. (optional, default to 50)</param>
        /// <returns>Task of RoleListResponse</returns>
        public async System.Threading.Tasks.Task<RoleListResponse> RolesGetAsync (string rolename = null, bool? enabled = null, string sort = null, int? offset = null, int? limit = null)
        {
             ApiResponse<RoleListResponse> localVarResponse = await RolesGetAsyncWithHttpInfo(rolename, enabled, sort, offset, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the roles. Returns the list of all roles. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="rolename">The role name to use as a filter. (optional)</param>
        /// <param name="enabled">Indicates whether to retrieve the active roles (true) or inactive roles (false). (optional)</param>
        /// <param name="sort">A comma separated list of fields to use for sorting the entries. Allowed field values are \&quot;name\&quot; and \&quot;description\&quot;. Fields can be prefixed by \&quot;+\&quot; and \&quot;-\&quot; to indicate, respectively, ascending and descending order.  Usage example: /roles?sort&#x3D;+name,-description  (optional)</param>
        /// <param name="offset">The number of entries to skip. Default is 0. (optional, default to 0)</param>
        /// <param name="limit">The maximum number of entries to return. Default is 50. (optional, default to 50)</param>
        /// <returns>Task of ApiResponse (RoleListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RoleListResponse>> RolesGetAsyncWithHttpInfo (string rolename = null, bool? enabled = null, string sort = null, int? offset = null, int? limit = null)
        {

            var localVarPath = ApiClient.ApiPathPrefix + "/roles";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new Dictionary<string, string>();
            var localVarHeaderParams = new Dictionary<string, string>(this.ApiClient.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (rolename != null) localVarQueryParams.Add("rolename", this.ApiClient.ParameterToString(rolename)); // query parameter
            if (enabled != null) localVarQueryParams.Add("enabled", this.ApiClient.ParameterToString(enabled)); // query parameter
            if (sort != null) localVarQueryParams.Add("sort", this.ApiClient.ParameterToString(sort)); // query parameter
            if (offset != null) localVarQueryParams.Add("offset", this.ApiClient.ParameterToString(offset)); // query parameter
            if (limit != null) localVarQueryParams.Add("limit", this.ApiClient.ParameterToString(limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RolesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RoleListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RoleListResponse) this.ApiClient.Deserialize(localVarResponse, typeof(RoleListResponse)));
            
        }

        /// <summary>
        /// Get a specific role. Returns the role specified by the &#x60;id&#x60; parameter. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the role.</param>
        /// <returns>RoleResponseData</returns>
        public RoleResponseData RolesIdGet (string id)
        {
             ApiResponse<RoleResponseData> localVarResponse = RolesIdGetWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a specific role. Returns the role specified by the &#x60;id&#x60; parameter. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the role.</param>
        /// <returns>ApiResponse of RoleResponseData</returns>
        public ApiResponse< RoleResponseData > RolesIdGetWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling RolesApi->RolesIdGet");

            var localVarPath = ApiClient.ApiPathPrefix + "/roles/{id}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new Dictionary<string, string>();
            var localVarHeaderParams = new Dictionary<string, string>(this.ApiClient.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (id != null) localVarPathParams.Add("id", this.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RolesIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RoleResponseData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RoleResponseData) this.ApiClient.Deserialize(localVarResponse, typeof(RoleResponseData)));
            
        }

        /// <summary>
        /// Get a specific role. Returns the role specified by the &#x60;id&#x60; parameter. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the role.</param>
        /// <returns>Task of RoleResponseData</returns>
        public async System.Threading.Tasks.Task<RoleResponseData> RolesIdGetAsync (string id)
        {
             ApiResponse<RoleResponseData> localVarResponse = await RolesIdGetAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a specific role. Returns the role specified by the &#x60;id&#x60; parameter. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the role.</param>
        /// <returns>Task of ApiResponse (RoleResponseData)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RoleResponseData>> RolesIdGetAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling RolesApi->RolesIdGet");

            var localVarPath = ApiClient.ApiPathPrefix + "/roles/{id}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new Dictionary<string, string>();
            var localVarHeaderParams = new Dictionary<string, string>(this.ApiClient.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (id != null) localVarPathParams.Add("id", this.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RolesIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RoleResponseData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RoleResponseData) this.ApiClient.Deserialize(localVarResponse, typeof(RoleResponseData)));
            
        }

        /// <summary>
        /// Gets the roles for a user. Returns the ordered list of role IDs for the specified user. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <returns>List&lt;Guid&gt;</returns>
        public GenericIdListDataResponse UsersIdRolesGet (string id)
        {
             ApiResponse<GenericIdListDataResponse> localVarResponse = UsersIdRolesGetWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the roles for a user. Returns the ordered list of role IDs for the specified user. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <returns>ApiResponse of List&lt;Guid&gt;</returns>
        public ApiResponse<GenericIdListDataResponse> UsersIdRolesGetWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling RolesApi->UsersIdRolesGet");

            var localVarPath = ApiClient.ApiPathPrefix + "/users/{id}/roles";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new Dictionary<string, string>();
            var localVarHeaderParams = new Dictionary<string, string>(this.ApiClient.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (id != null) localVarPathParams.Add("id", this.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UsersIdRolesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenericIdListDataResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GenericIdListDataResponse) this.ApiClient.Deserialize(localVarResponse, typeof(GenericIdListDataResponse)));
            
        }

        /// <summary>
        /// Gets the roles for a user. Returns the ordered list of role IDs for the specified user. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <returns>Task of List&lt;Guid&gt;</returns>
        public async System.Threading.Tasks.Task<GenericIdListDataResponse> UsersIdRolesGetAsync (string id)
        {
             ApiResponse<GenericIdListDataResponse> localVarResponse = await UsersIdRolesGetAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets the roles for a user. Returns the ordered list of role IDs for the specified user. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <returns>Task of ApiResponse (List&lt;Guid&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GenericIdListDataResponse>> UsersIdRolesGetAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling RolesApi->UsersIdRolesGet");

            var localVarPath = ApiClient.ApiPathPrefix + "/users/{id}/roles";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new Dictionary<string, string>();
            var localVarHeaderParams = new Dictionary<string, string>(this.ApiClient.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (id != null) localVarPathParams.Add("id", this.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UsersIdRolesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenericIdListDataResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GenericIdListDataResponse) this.ApiClient.Deserialize(localVarResponse, typeof(GenericIdListDataResponse)));
            
        }

        /// <summary>
        /// Updates the roles for a user. Updates the list of role IDs for the specified user. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <param name="body">The unordered list of roles for the specified user.</param>
        /// <returns></returns>
        public void UsersIdRolesPut (string id, List<Guid> body)
        {
             UsersIdRolesPutWithHttpInfo(id, body);
        }

        /// <summary>
        /// Updates the roles for a user. Updates the list of role IDs for the specified user. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <param name="body">The unordered list of roles for the specified user.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> UsersIdRolesPutWithHttpInfo (string id, List<Guid> body)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling RolesApi->UsersIdRolesPut");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling RolesApi->UsersIdRolesPut");

            var localVarPath = ApiClient.ApiPathPrefix + "/users/{id}/roles";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new Dictionary<string, string>();
            var localVarHeaderParams = new Dictionary<string, string>(this.ApiClient.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (id != null) localVarPathParams.Add("id", this.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UsersIdRolesPut", localVarResponse);
                if (exception != null) throw exception;
            }

            
            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Updates the roles for a user. Updates the list of role IDs for the specified user. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <param name="body">The unordered list of roles for the specified user.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UsersIdRolesPutAsync (string id, List<Guid> body)
        {
             await UsersIdRolesPutAsyncWithHttpInfo(id, body);

        }

        /// <summary>
        /// Updates the roles for a user. Updates the list of role IDs for the specified user. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The ID of the user.</param>
        /// <param name="body">The unordered list of roles for the specified user.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> UsersIdRolesPutAsyncWithHttpInfo (string id, List<Guid> body)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling RolesApi->UsersIdRolesPut");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling RolesApi->UsersIdRolesPut");

            var localVarPath = ApiClient.ApiPathPrefix + "/users/{id}/roles";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new Dictionary<string, string>();
            var localVarHeaderParams = new Dictionary<string, string>(this.ApiClient.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept =this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (id != null) localVarPathParams.Add("id",this.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody =this.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UsersIdRolesPut", localVarResponse);
                if (exception != null) throw exception;
            }

            
            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
