/* 
 * Qlik NPrinting API
 *
 * You can extend your reporting system by using the Qlik NPrinting API. This API provides endpoints to perform operations on apps, On-Demand requests and results, reports, filters, and so on.  For all requests, the data returned is filtered based on user permissions. That is, if a user is not authorized to access a certain object, that object is not returned in the reponse.  API Stability: Experimental.  Deprecation period: None. Can change at any point and should be used only to evaluate upcoming functionality.     
 *
 * OpenAPI spec version: 0.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Qlik.NPrinting.Rest.Client.Model
{
    /// <summary>
    /// FilterRequest
    /// </summary>
    [DataContract]
    public partial class FilterRequest :  IEquatable<FilterRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterRequest" /> class.
        /// </summary>
        [JsonConstructor]
        protected FilterRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterRequest" /> class.
        /// </summary>
        /// <param name="Appid">The unique identifier of the app. (required).</param>
        /// <param name="Enabled">Indicates whether the filter is enabled. (required).</param>
        /// <param name="Name">The name of the filter. (required).</param>
        /// <param name="Description">The description of the filter..</param>
        /// <param name="Fields">Fields (required).</param>
        public FilterRequest(Guid? Appid = default(Guid?), bool? Enabled = default(bool?), string Name = default(string), string Description = default(string), List<FilterField> Fields = default(List<FilterField>))
        {
            // to ensure "Appid" is required (not null)
            if (Appid == null)
            {
                throw new InvalidDataException("Appid is a required property for FilterRequest and cannot be null");
            }
            else
            {
                this.Appid = Appid;
            }
            // to ensure "Enabled" is required (not null)
            if (Enabled == null)
            {
                throw new InvalidDataException("Enabled is a required property for FilterRequest and cannot be null");
            }
            else
            {
                this.Enabled = Enabled;
            }
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for FilterRequest and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            // to ensure "Fields" is required (not null)
            if (Fields == null)
            {
                throw new InvalidDataException("Fields is a required property for FilterRequest and cannot be null");
            }
            else
            {
                this.Fields = Fields;
            }
            this.Description = Description;
        }
        
        /// <summary>
        /// The unique identifier of the app.
        /// </summary>
        /// <value>The unique identifier of the app.</value>
        [DataMember(Name="appid", EmitDefaultValue=false)]
        public Guid? Appid { get; set; }
        /// <summary>
        /// Indicates whether the filter is enabled.
        /// </summary>
        /// <value>Indicates whether the filter is enabled.</value>
        [DataMember(Name="enabled", EmitDefaultValue=false)]
        public bool? Enabled { get; set; }
        /// <summary>
        /// The name of the filter.
        /// </summary>
        /// <value>The name of the filter.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// The description of the filter.
        /// </summary>
        /// <value>The description of the filter.</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }
        /// <summary>
        /// Gets or Sets Fields
        /// </summary>
        [DataMember(Name="fields", EmitDefaultValue=false)]
        public List<FilterField> Fields { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FilterRequest {\n");
            sb.Append("  Appid: ").Append(Appid).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as FilterRequest);
        }

        /// <summary>
        /// Returns true if FilterRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of FilterRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FilterRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Appid == other.Appid ||
                    this.Appid != null &&
                    this.Appid.Equals(other.Appid)
                ) && 
                (
                    this.Enabled == other.Enabled ||
                    this.Enabled != null &&
                    this.Enabled.Equals(other.Enabled)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.Description == other.Description ||
                    this.Description != null &&
                    this.Description.Equals(other.Description)
                ) && 
                (
                    this.Fields == other.Fields ||
                    this.Fields != null &&
                    this.Fields.SequenceEqual(other.Fields)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Appid != null)
                    hash = hash * 59 + this.Appid.GetHashCode();
                if (this.Enabled != null)
                    hash = hash * 59 + this.Enabled.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.Description != null)
                    hash = hash * 59 + this.Description.GetHashCode();
                if (this.Fields != null)
                    hash = hash * 59 + this.Fields.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
