/* 
 * Qlik NPrinting API
 *
 * You can extend your reporting system by using the Qlik NPrinting API. This API provides endpoints to perform operations on apps, On-Demand requests and results, reports, filters, and so on.  For all requests, the data returned is filtered based on user permissions. That is, if a user is not authorized to access a certain object, that object is not returned in the reponse.  API Stability: Experimental.  Deprecation period: None. Can change at any point and should be used only to evaluate upcoming functionality.     
 *
 * OpenAPI spec version: 0.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;
using Qlik.NPrinting.Rest.Client.Api;
using Qlik.NPrinting.Rest.Client.Model;

namespace Qlik.NPrinting.Rest.Client.Test.Api
{
    /// <summary>
    ///  Class for testing ReportsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    class ReportsApiTests : BaseNPrintingClinetTest
    {
        private ReportsApi _instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            _instance = new ReportsApi(NprintingApiClient);
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
           Assert.IsInstanceOf<ReportsApi>(_instance, "response is ReportsApi");
        }

        
        /// <summary>
        /// Test ReportsGet
        /// </summary>
        [Test]
        public void ReportsGetAllTest()
        {
            var response = _instance.ReportsGet();
            Assert.IsInstanceOf<ReportListResponse> (response, "response is ReportListResponse");
        }
        
        /// <summary>
        /// Test ReportsReportIdGet
        /// </summary>
        [Test]
        public void ReportsReportIdGetTest()
        {
            var reportList = _instance.ReportsGet();
            var reportId = reportList.Data.Items[0].Id.ToString();
            var response = _instance.ReportsReportIdGet(reportId);
            Assert.IsInstanceOf<ReportResponse> (response, "response is ReportResponse");
            Assert.That(response.Data.Id.ToString(), Is.EqualTo(reportId));
        }
    }
}
